cargo-features = ["profile-rustflags", "trim-paths"]  # Special compiler features for customizing build

[package]
name = "slint_widgets"
version = "0.1.0"
edition = "2024"
authors = ["Smirnov Anton <abcsmir.ant@yandex.ru>"]  

[lib]
crate-type = ["cdylib"]

[dependencies]
slint = { version = "1.14.1", default-features = false, features = [
    "renderer-femtovg",     # render-software will have troubles wil clip and rotate for dropdown widget 
    "backend-winit",        # Engine for window and mouse handling
    "compat-1-2",           # Compatibility
]}

# /============== WASM ==============
[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { version = "0.2" } # Facilitates high-level interactions between WASM and JavaScript.

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]
# \_____________________________________

[build-dependencies]
slint-build = "1.14.1"


# -------------------------
[profile.dev]
incremental = true              # Enable incremental compilation (only changed parts)
rustflags = ["-Zthreads=8"]     # Compiler flags: use 8 threads for compilation

[profile.release]
codegen-units = 1   # How many program parts to compile simultaneously (less = less memory, more = faster)
lto = true          # True: compiler sees entire program during final linking, allows more global optimizations
opt-level = "z"     # Optimization level, z - minimum file size
panic = "abort"     # Error behavior: "abort" - immediately stop the program
strip = true        # Remove debug information from the executable
trim-paths = "all"  # Remove excess paths from debug info
