
import { Button, Palette } from "std-widgets.slint";

export component SidePanel inherits Rectangle {
    in property <bool> position_right: false;
    in property <length> panel_border_radius: 0px;
    in property <brush> panel_background: Palette.background;
    in property <length> panel_width: 500px;
    in property <length> panel_spacing: 10px;
    in property <length> panel_padding: 12px;
    
    in-out property <bool> shown: false;

    width: 100%;
    height: 100%;
    z: 100;

    bg := Rectangle {
        width: 100%;
        height: 100%;
        clip: true;
        background: #000000.with_alpha(root.shown ? 50% : 0%);
        animate background { duration: 250ms; easing: ease; }

        touch_area := TouchArea {
            enabled: root.shown;
            clicked => { root.shown = false; }
        }
    }

    panel := TouchArea {
        width: min(root.panel_width, root.width * 0.75);  // panel_width but not bigger than 65%
        x: root.position_right ? (root.shown ? parent.width - self.width : parent.width) : (root.shown ? 0 : -self.width);
        y: 0;
        height: 100%;
        animate x { duration: 200ms; easing: cubic-bezier(0, 0, 0, 1); }

        Rectangle {
            background: root.panel_background;
            border-bottom-left-radius: position_right? panel_border_radius: 0;
            border-top-left-radius: position_right? panel_border_radius: 0;
            border-bottom-right-radius: position_right? 0: panel_border_radius;
            border-top-right-radius: position_right? 0: panel_border_radius;

            layout := VerticalLayout {
                alignment: start;
                padding: root.panel_padding;
                spacing: root.panel_spacing;
                @children
            }
        }
    }
}