import { Palette, LineEdit, ScrollView, Button, TabWidget } from "std-widgets.slint";

import { LabelBorder } from "widgets/label_border.slint";
import { Dropdown } from "widgets/dropdown/dropdown.slint";
import { WheelPicker } from "widgets/wheel_picker.slint";
import { HR } from "widgets/hr.slint";
import { SidePanel } from "widgets/side_panel.slint";


export component Main inherits Window {
    in property <length> window_padding: 20px;  // const for full_width and define main vertical layout padding
    in property <length> full_width: root.width - (window_padding*2) - 4px;  // size for elems which need to 100% width but padding*2 and scrollbar(4px)
    
    // min-width: 800px;
    min-height: 600px;
    background: Palette.background;
    
    TabWidget {
        Tab {
            title: "LabelBorder";
            VerticalLayout {
                padding: 20px;
                spacing: 40px;
                alignment: start;

                // ------------- LabelBorder -------------
                LabelBorder {
                    Text { text: "One two three four five"; }
                }

                LabelBorder {
                    title: "LabelBorder #2";
                    Button { text: "Lorem ipsum"; }
                }

                LabelBorder {
                    title: "LabelBorder #3";
                    parent-background: root.background;  // if your main background is not Palette.background - u can config it manually for label background
                    border-radius: 15px;
                    label-font-size: 18px;
                    // width: full_width;

                    Text { text: "Different types of elems"; } 
                    LineEdit { placeholder-text: "And as many as you want"; }
                    Text { text: "It will be min possible width and height by defalut"; }
                }

                LabelBorder {
                    title: "LabelBorder #4";
                    width: 100%;  // full width, not fit-content
                    label-font-size: 20px;
                    border-radius: 15px;

                    VerticalLayout {
                        Text { text: "Choose the answer"; font-size: 18px;}
                        HorizontalLayout {
                            spacing: 10px;
                            for letter[indx] in ["A", "B", "C"]: Button {
                                text: "\{letter} : \{indx}";
                            }
                        }
                    }
                }
            }
        }


        Tab {
            title: "Dropdown";
            VerticalLayout {
                padding: 20px;
                spacing: 40px;
                alignment: start;

                // ------------- Dropdown -------------
                Dropdown {
                    title: "Dropdown #1";
                    Text { text: "Thank you for your question!"; }
                }

                Dropdown {
                    title: "Dropdown #2";
                    title-font-size: 14px;
                    border-radius: 10px;
                    header-background: false;

                    LineEdit { placeholder-text: "Some setting"; } Button { text: "A button"; } Text { text: "Last item"; }
                }

                Dropdown {
                    title: "Dropdown #3";
                    title-font-size: 20px;
                    border-radius: 2px;
                    header-background: true;
                    expanded: true;
                    width: 100%;

                    LineEdit { placeholder-text: "Open by default"; }
                    Button { text: "And full width"; }
                    Text { text: "And have 3 elems"; }
                }
            }
        }


        Tab {
            title: "HR";
            VerticalLayout {
                padding: 20px;
                alignment: start;

                // ------------- HR -------------
                Text { text: "HR #1"; }
                HR {}
                Text { text: "HR #2"; }
                HR {
                    hr-width: 75%;
                    hr-height: 5px;
                    hr-background: Palette.accent-background;
                    hr-border-radius: 5px;
                    vertical-padding: 45px;
                }
                Text { text: "HR #3"; }
                HR {
                    hr-width: 50%;
                    hr-height: 10px;
                    hr-background: #22aa5544;
                }
            }
        }
        Tab {
            title: "WheelPicker";
            VerticalLayout {
                padding: 20px;
                spacing: 80px;
                alignment: start;

                // ------------- WheelPicker #1 -------------
                property <int> selected-hour: 0;
                property <int> selected-minute: 0;
                property <int> selected-second: 0;

                property <[string]> hours-model: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23",];
                property <[string]> minutes-model: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",];
                property <[string]> seconds-model: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",];

                VerticalLayout {
                    spacing: 10px;
                    HorizontalLayout {
                        alignment: center;
                        spacing: 10px;

                        WheelPicker {
                            sections: 5;
                            model: hours-model;
                            selected(index) => { selected-hour = index; }
                        }
                        WheelPicker {
                            sections: 5;
                            model: minutes-model;
                            selected(index) => { selected-minute = index; }
                        }
                        WheelPicker {
                            sections: 5;
                            model: seconds-model;
                            selected(index) => { selected-second = index; }
                        }
                    }

                    Button {
                        text: "Show time";
                        clicked => {
                            debug("\{selected-hour} : \{selected-minute} : \{selected-second}");
                        }
                    }
                }
                
                // ------------- WheelPicker #2 -------------
                property <int> selected-day: 0;
                // property <int> selected-hour: 0;  // already in WheelPicker #1
                // property <int> selected-minute: 0;  // already in WheelPicker #1

                property <[string]> dow-model: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
                // already in WheelPicker #1
                // property <[string]> hours-model: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"];
                // property <[string]> minutes-model: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",];

                VerticalLayout {
                spacing: 20px;
                HorizontalLayout {
                    alignment: center;
                    spacing: 10px;

                    VerticalLayout {
                        spacing: 10px;
                        WheelPicker {
                            width: 50px;
                            sections: 3;
                            reverse-scroll: true;
                            accent-color: gray.with-alpha(0.3);
                            model: dow-model;
                            selected(index) => { selected-day = index; }
                        }
                        HorizontalLayout { alignment: center; Text { text: "Day"; font-size: 14px; }} 
                    }
                    VerticalLayout {
                        spacing: 10px;
                        WheelPicker {
                            width: 150px;
                            sections: 5;
                            model: hours-model;
                            reverse-scroll: true;
                            accent-color: red;
                            selected(index) => { selected-hour = index; }
                        }
                        HorizontalLayout { alignment: center; Text { text: "Hour"; font-size: 14px; }} 
                    }
                    VerticalLayout {
                        spacing: 10px;
                        WheelPicker {
                            sections: 2;
                            model: minutes-model;
                            selected(index) => { selected-minute = index; }
                        }
                        HorizontalLayout { alignment: center; Text { text: "Minute"; font-size: 14px; }} 
                    }
                }

                Button {
                    text: "Show";
                    clicked => {
                        debug("\{dow-model[selected-day]} \{selected-hour} : \{selected-minute}");
                    }
                }
                }
            }
        }


        Tab {
            title: "SidePanel";
            VerticalLayout {
                padding: 20px;
                spacing: 40px;
                alignment: start;

                Button {
                    text: "SidePanel #1";
                    clicked => {
                        sidePanel1.shown = !sidePanel1.shown;
                    }
                }

                Button {
                    text: "SidePanel #2";
                    clicked => {
                        sidePanel2.shown = !sidePanel2.shown;
                    }
                }

            }
        }
    }
    // not in tabs widget, cuz need to window level, popup over all layers
    sidePanel1 := SidePanel {
        Text { text: "SidePanel #1"; }
    }
    sidePanel2 := SidePanel {
        position_right: true;
        panel_width: 300px;
        panel_border_radius: 15px;
        panel_padding: 25px;
        panel_spacing: 25px;

        Text { text: "SidePanel #2"; }
        Button { text: "Inside Button"; 
            clicked => {sidePanel2.shown = false;}
        }
    }
}