name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly  # the cargo feature `profile-rustflags` requires a nightly version of Cargo
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Clean WASM directory
        run: rm -rf web/static/wasm

      - name: Build WASM package
        run: wasm-pack build --release --target web --out-dir web/static/wasm

      - name: Clean up build artifacts
        run: rm -f web/static/wasm/package.json web/static/wasm/.gitignore web/static/wasm/*.ts

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: web
